### PR TITLE
Add MonadError instances for ContT

### PR DESCRIPTION
**Pull request by Atry**
`ContT e (ContT r (a lot of other transformers...))` could be more efficient than `ExceptT e (ContT r (a lot of other transformers...))`, because `>>=` and `return` for `ContT e (ContT r m)` are as efficient as `Cont`, while the performance of `ExceptT` depend on the number of layers of transformers.

### CODE REVIEW

**Comment by chessai** [comment]
We certainly do not want overlapping instances here. We need to pick just one of these definitions.

**Comment by Atry** [comment]
The purpose of overlapping instances is to support multiple `MonadError` instances, similar to https://github.com/haskell/mtl/pull/73

Suppose we have a type:
``` Haskell
type X = ContT IOException
       $ ContT AllocationLimitExceeded
       $ ContT Int IO
```

It should support both the following `MonadError`s:

* `MonadError AllocationLimitExceeded X`
* `MonadError IOException X`

**Comment by chessai** [comment]
I'm not a fan of overlapping instances in general, especially not with FunDeps. Overlapping allows you to subvert some of the guarantees that FunDeps give you in the first place, those guarantees which have thus far been a trademark of MTL typeclasses. See https://gitlab.haskell.org/ghc/ghc/issues/15927 for some more discussion.

**Comment by Atry** [comment]
Then how can we gain the ability of multiple MonadError?

chessai <notifications@github.com>于2020年1月18日 周六下午1:27写道：

**Comment by Atry** [comment]
I did not really understand the initial purpose of the function dependency `m -> e` on `MonadError`. Why not just remove `m -> e`?

**Comment by Lysxia** [comment]
> I did not really understand the initial purpose of the function dependency m -> e on MonadError. Why not just remove m -> e?

The dependency is there for type inference, otherwise you would have to annotate error types in a lot of places. Overlapping instances, which is your motivation for removing those dependencies, can also be quite unintuitive, which is a fairly strong reason not to use them.

For instance, this overlapping instance makes it impractical to use `ContT` with a `MonadError` constraint on an abstract `m`:

```
-- Doesn't typecheck
throwe :: MonadError e m => e -> ContT r m a
throwe = throwError
```

**Comment by Atry** [comment]
It typechecks:
https://repl.it/repls/CornsilkStrongDonateware
``` Haskell
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE IncoherentInstances #-}

class MonadError e m where
  throwError :: e -> m a

newtype ContT r m a = ContT { runContT :: (a -> m r) -> m r }
instance {-# OVERLAPPING #-} Monad m => MonadError e (ContT e (ContT r m)) where
  throwError e = undefined

instance MonadError e m => MonadError e (ContT r m)  where
  throwError e = undefined

throwe :: MonadError e m => e -> ContT r m a
throwe = throwError

main = return ()
```

**Pull request closed without merging**
