### PR TITLE
Add MonadWriter instance for ContT

### PR DESCRIPTION
**Pull request by Atry**
Similar to https://github.com/haskell/mtl/pull/70

### CODE REVIEW

**Comment by chessai** [comment]
Also similarly to #70, why not using the underlying `MonadWriter w m` instance?

**Comment by chessai** [comment]
(The above question was rhetorical, you can't.)

But I'm not sure that we do want to lift reader in this way? Thoughts @haskell/core-libraries-committee ?

**Comment by gwils** [comment]
This instance seems weird to me. Besides which it would be confusing for an MTL class to have an instance that wasn't the expected lifting.

**Comment by chessai** [comment]
non-canonical, closing

**Pull request closed without merging**
